### ISSUE TITLE
is it possible to decrease time between two clicks?

### ISSUE THREAD

**Issue by trofey** [webextensions/close-tab-by-double-right-click#10]
I often press two single clicks and extension detects it like a double. Is it possible to decrease time between two clicks?

**Comment by webextensions** [comment]
The fix is now available from v1.1.0 onwards on Google Web Store :+1:

@trofey
To configure the extension, please visit "chrome://extensions/" > "Details" (for this extension) > "Extension options"

**Comment by trofey** [comment]
will it be available for firefox?

**Comment by webextensions** [comment]
@trofey 

A buggy version was published on Firefox. That issue has now been fixed with the latest update.

The feature is now available from v1.1.1 onwards on Firefox Add-ons Store :+1:
