### ISSUE TITLE
No longer works with Firefox 95 on Linux

### ISSUE THREAD

**Issue by stephendavidmarsh** [webextensions/close-tab-by-double-right-click#11]
The double right click to close extension no longer works with Firefox 95 on Linux. This occurs with any web page. It was working with Firefox 94, so the recent Firefox update broke it.

**Comment by webextensions** [comment]
@stephendavidmarsh 
Thank you for the report.

Unfortunately, it seems to be a bug / behavioral change from Firefox's end. Now, after a right click (followed by opening of context menu), Firefox doesn't let the webpage receive any more left or right click till when the mouse isn't moved. In fact, it doesn't even close the context menu if the user does a right click followed by left click, without moving the mouse.

Note: The above mentioned observations are for Firefox 95.0.2 with Ubuntu Linux.

**Overall, it means that if Firefox doesn't change its behavior back, this extension wouldn't be able to function with the current approach of double right click**.

Keeping this issue open for revisit at a later time.

**Comment by webextensions** [comment]
Fixed with a behavioral change as described in https://github.com/webextensions/close-tab-by-double-right-click/issues/12
