### ISSUE TITLE
Broken as of FF 102.0

### ISSUE THREAD

**Issue by Arkz86** [webextensions/close-tab-by-double-right-click#12]
As per title

[edit]
As Reibies has discovered it will still work as long as you move the cursor between clicks.

**Comment by ZZKJInc** [comment]
Yep, 101 ok, 102 no go

Pity, great little extention...

**Comment by Reibies** [comment]
It works for me if I click in different parts of the screen, so I think it's the context menu messing it up.

**Comment by Arkz86** [comment]
> 

On 102? I noticed a comment on the addons site saying it's broken too.

**Comment by Reibies** [comment]
Yes. on 102. I have been doing that all day, I just can't leave my mouse in the same spot each click.

**Comment by Arkz86** [comment]
> Yes. on 102. I have been doing that all day, I just can't leave my mouse in the same spot each click.

Can confirm it will work on 102 if you move the mouse. What a weird issue.

I switched to Rights to Close EX which doesn't need the mouse moving, but disables the context menu unless you hold ctrl so that's quite annoying.

**Comment by webextensions** [comment]
@Arkz86 @ZZKJInc @Reibies 
Thank you for the report and the discussions. Apparently, the new version of Firefox has changed the right-click behavior to a certain extent which affects this extension.

The workaround solution that has been implemented is that another gesture of left-click-immediately-followed-by-right-click has been introduced.

So, now onwards, a user can utlize:
* Double-right-click to close tab for non-Firefox browsers
* **Left-click-immediately-followed-by-right-click for all browsers (including Firefox)**

The documentation has been updated and the updated extension is now available at the Mozilla add-ons store.

PS / Bonus tip:
As an unintended side-effect (as **observed in Firefox 102 on Ubuntu 22.04**) of the Firefox behavior and updated extension code, if one wishes to close multiple tabs, for closing the first tab, left-click-immediately-followed-by-right-click can be used and as the focus shifts to another tab, the newly focused tab(s) can be closed by a single-right-click itself (with the single-right-click done quickly in the flow of closing multiple tabs). Note: This behavior may be updated later on if any bugs/issues are noticed.

**Comment by Arkz86** [comment]
Wow this seems to have made it even worse. Having to move the mouse between right clicks was a minor annoyance I could get used to, but now, as long as I've left clicked at some point, each right click, no matter how much later, closes the tab I'm on. I could be half way down a page and right click something and it closes the tab. Only way I've found around it so far is holding right click for a while opens the context menu without closing the tab... Ugh. Is there a way to rollback addons on FF?

**Comment by webextensions** [comment]
@Arkz86
Another improvement has been attempted and it is now available with v1.1.3

**Comment by webextensions** [comment]
**Note:** The code which was added to workaround this issue (https://github.com/webextensions/close-tab-by-double-right-click/commit/ccade765586f7d938896c7948956fb816899a402 and https://github.com/webextensions/close-tab-by-double-right-click/commit/0bbd6b67280888995450212085e8bd13978d8c9f) has now been removed as mentioned in https://github.com/webextensions/close-tab-by-double-right-click/issues/17
