### ISSUE TITLE
extension ban

### ISSUE THREAD

**Issue by tasic99** [webextensions/close-tab-by-double-right-click#16]
as on 2024-12-20 the extension is banned and is disabled in Chrome
do you have any idea how to fix this situation

**Comment by webextensions** [comment]
@tasic99
Thank you for the report :smile: 

The extension has been refactored to use the new Manifest V3 with https://github.com/webextensions/close-tab-by-double-right-click/commit/397593f9352eda3b7c4c4b6fab7da34ae8e40f4f and some other later commits.

The extension has been updated at the Chrome Web Store and it should be available again there.
