### ISSUE TITLE
Firefox leaves context menu open

### ISSUE THREAD

**Issue by share3141** [webextensions/close-tab-by-double-right-click#7]
I have FF 80.0b2 and double-right-click 1.0.6. When I double-right-click on a web page the page closes fine but the context menu is left open. I have this extension installed in Edge and Brave and do not have the same issue.  Nice extension.

**Comment by webextensions** [comment]
Fixed with a behavioral change as described in https://github.com/webextensions/close-tab-by-double-right-click/issues/12
