### ISSUE TITLE
Causes error during jQuery ajax

### ISSUE THREAD

**Issue by hawkeyetwolf** [webextensions/close-tab-by-double-right-click#8]
With this extension enabled, I get the following error in console, preventing button click that's supposed to submit via jQuery ajax:
> Uncaught Error: Permission denied to access property "apply"

**Comment by webextensions** [comment]
@hawkeyetwolf 
Since the issue would be specific to some particular page, can you provide the public URL of that page ?
If it is not a public page, then we would need to figure out some other way to replicate the issue.

**Comment by hawkeyetwolf** [comment]
Thanks for the quick reply @webextensions. Unfortunately it's not a public-facing page (CMS content edit form). I'll just go ahead and close this issue but if anyone else comes across this they can re-open post a URL.
